### ISSUE TITLE
`updateTransportMethod` doesn't resolve when called multiple times successively before iframe loads

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/eth-ledger-bridge-keyring#70]
If `updateTransportMethod` is called a second time before the iframe loads and before the first call resolves, the first call will never resolve.

We should queue up delayed promises to ensure none of them fail to resolve. Maybe with some timeout handling or max queue size to handle bizarre usage correctly.

**Comment by mikesposito** [comment]
@Gudahtt As an alternative solution to queues, do you think we could wait for the iframe to be ready when calling `init`, so that we can assume that the bridge (and the iframe) has been already setup in subsequent calls to `updateTransportMethod`? This would allow us to remove this delayed promise pattern altogether

**Comment by Gudahtt** [comment]
Yes I think so! There was no `init` method when I wrote this issue, that's why that wasn't suggested.
